server:
  port: 8010

spring:
  application:
    name: user-service

  cloud:
    nacos:
      discovery:
        server-addr: 47.105.146.74:8848

    alibaba:
      seata:
        tx-service-group: default

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.105.146.74:3306/ac_mall_cloud_user_service_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =GMT%2B8
    username: user_service_u
    password: user_service_PWD_123

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
